version: '3.9'

services:
    mariadb:
        container_name: 'mariadb'
        restart: always
        image: mariadb:10.6
        environment:
            MYSQL_DATABASE: myapp_db
            MYSQL_USER: myapp_user
            MYSQL_PASSWORD: myapp_pass
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - myapp_network
    myapp:
        container_name: 'myapp'
        restart: always
        image: bitnami/laravel:9
        ports:
            - '8000:8000'
        environment:
            DB_HOST: mariadb
            DB_PORT: 3306
            DB_DATABASE: myapp_db
            DB_USERNAME: myapp_user
            DB_PASSWORD: myapp_pass
        volumes:
            - .:/app
        networks:
            - myapp_network
networks:
    myapp_network:
        name: myapp_network
        driver: bridge
